%% Add Assignment Folders in Path

addpath('Assignment1/');
addpath('Assignment2/');
addpath('Assignment3/');
addpath('Assignment4/');
addpath('util/');
addpath('data/');


%% Set Default Graphics Settings

set(groot,  'DefaultLineLineWidth', 2.5, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
            'DefaultAxesFontName', 'LaTeX', ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1.5, ...
            'DefaultStemLineWidth', 2.5, ...
            'DefaultStemMarker', 'none', ...
            'DefaultAxesFontSize', 16, ...
            'DefaultAxesBox', 'on', ...
            'DefaultAxesColor', [1, 1, 1], ...
            'DefaultFigureColor', [1, 1, 1], ...
            'DefaultFigureInvertHardcopy', 'off', ...
            'DefaultFigurePaperUnits', 'inches', ...
            'DefaultFigureUnits', 'inches', ...
            'DefaultFigurePaperPosition', [0, 0, 5, 3], ...
            'DefaultFigurePaperSize', [6.5, 3], ...
            'DefaultFigurePosition', [0.1, 0.1, 6.4, 2.9], ...
            'DefaultLineMarkerSize', 20, ...
            'DefaultAxesFontName', 'Palatino');

        
%% Global Variables Initialisation (all capital)
COLORS = get(groot, 'factoryAxesColorOrder');


%% Environment State

% set default seed
rng(0);